
CREATE USER 'util1'@'%' IDENTIFIED BY '1234';
CREATE USER 'util2'@'%' IDENTIFIED BY '1234';
CREATE USER 'util3'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES  ON HOTEL.* TO 'util1'@'%' IDENTIFIED BY '1234';
GRANT SELECT ON HOTEL TO 'util2'@'%' IDENTIFIED BY '1234';
GRANT SHOW ON HOTEL.station TO 'util3'@'%' IDENTIFIED BY '1234'

SHOW GRANTS FOR 'util1'@'%';
SHOW GRANTS FOR 'util2'@'%';
SHOW GRANTS FOR 'util3'@'%';

